controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - ExtampFlex
      - AddampAbd
      - Elbow
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_base_joint
      - gripper_l_joint
      - gripper_r_joint
initial:  # Define initial robot poses per group
  - group: hand
    pose: open