arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ExtampFlex
    - AddampAbd
    - Elbow
  gains:
    ExtampFlex:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    AddampAbd:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_base_joint
    - gripper_l_joint
    - gripper_r_joint
  gains:
    gripper_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_l_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_r_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1