arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ExtampFlex
    - AddampAbd
    - Elbow
  gains:
    ExtampFlex:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    AddampAbd:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
  constraints:
    goal_time: &goal_time_constraint 4.0
    stopped_velocity_tolerance: 1.0
    arm_joint_0:
      goal: &goal_pos_constraint 0.5
      trajectory: &trajectory_pos_constraint 1.0
    arm_joint_1:
      goal: *goal_pos_constraint
      trajectory: *trajectory_pos_constraint
    arm_joint_2:
      goal: *goal_pos_constraint
      trajectory: *trajectory_pos_constraint
    arm_joint_3:
      goal: *goal_pos_constraint
      trajectory: *trajectory_pos_constraint
