arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ExtampFlex
    - AddampAbd
    - Elbow
  gains:
    ExtampFlex:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    AddampAbd:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 4.0
    stopped_velocity_tolerance: 1.0

  # Gripper Controll
gripper_base_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_base_joint
  pid: {p: 200.0, i: 0.0, d: 0.0}

gripper_l_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_l_joint
  pid: {p: 200.0, i: 0.0, d: 0.0}

gripper_r_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_r_joint
  pid: {p: 200.0, i: 0.0, d: 0.0}